dex:
  enabled: false
server:
  ingress:
    enabled: true
    https: false
    hosts:
      - argocd.k8s-frambozen.net
  extraArgs:
    - --insecure
  config:
    repositories: |
      - type: helm
        name: argocd
        url: https://argoproj.github.io/argo-helm