apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-avp-plugin
data:
  avp-helm.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command: 
            - sh
            - "-c"
            - "find . -name 'helm-application.yaml' && find . -name 'values.yaml'" ]
      generate:
        command:
          - sh
          - "-c"
          - |
            helm template $ARGOCD_APP_NAME --version $ARGOCD_ENV_HELM_CHART_VERSION --repo $ARGOCD_ENV_HELM_REPO_URL $ARGOCD_ENV_HELM_CHART_NAME --include-crds -n $ARGOCD_APP_NAMESPACE -f $ARGOCD_ENV_HELM_VALUES_FILE |
            argocd-vault-plugin generate - -c /home/argocd/cmp-server/config/vault-configuration.yaml
      lockRepo: false

  avp-kustomize.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - kustomization.yml
      generate:
        command:
          
          - sh
          - "-c"
          - "kustomize build . | argocd-vault-plugin generate - -c /home/argocd/cmp-server/config/vault-configuration.yaml"
      lockRepo: false
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - "."
          - "-c"
          - /home/argocd/cmp-server/config/vault-configuration.yaml
      lockRepo: false 


