# code language=ansible
---
- name: Empty repository project url list
  ansible.builtin.set_fact:
    project_repo_urls: []

- name: Extract the different projects for the list of repositories used for the application sets
  ansible.builtin.set_fact:
    repositories: "{{ repositories | default({}) |
      combine({(item.path | split('/'))[1]: item.scheme + '://' + item.netloc + '/' + (item.path | split('/'))[1]}) }}"
  loop: "{{ argocd_application_sets | map(attribute='repo_url') | map('urlsplit') }}"

- name: Add argocd repository credential templates
  kubernetes.core.k8s:
    state: present
    namespace: "{{ argocd_namespace }}"
    template:
      - path: argocd_repository.j2
  loop: "{{ repositories | dict2items(key_name='name', value_name='url') + argocd.github.projects }}"
  loop_control:
    loop_var: repository
