---
# code language=ansible
argocd_helm_repo_name: argo
argocd_helm_repo_chart: "https://argoproj.github.io/argo-helm"
argocd_helm_chart_version: 7.5.2
argocd_helm_chart: "{{ argocd_helm_repo_name }}/argo-cd"

argocd_namespace: argocd
argocd_alias: argocd

argocd_helm_ingress: true

# Define the Vault server that will be used by the argo cd vault plugin.
argocd_vault_server: "http://192.168.1.72:8205"

# Define the images that should be used by plugins:
argocd_init_container_images:
  download_tools: "registry.shs.k8s-frambozen.nl/cdinnovatie/kubectl:1.24.16-0"
argocd_extra_container_images:
  k8s-frambozen_helm_avp: "registry.shs.k8s-frambozen.nl/cdinnovatie/kubectl:1.24.16-0"
  k8s-frambozen_kustomize: "registry.shs.k8s-frambozen.nl/cdinnovatie/kubectl:1.24.16-0"

argocd_webhook:
  name: "ArgoCD {{ universe.environment | upper }} webhook"
  url: "https://argocd.apps.{{ universe.environment }}.cloud.cjib.nl/api/webhook"
  event: "repo:refs_changed"
