# code language=ansible
argocd_helm_repo_name: helm-argo-cd
argocd_helm_repo_chart: "{{ cjib_nexus_repository_url }}/{{ argocd_helm_repo_name }}"
argocd_helm_chart_version: 5.46.7
argocd_helm_chart: "{{ argocd_helm_repo_name }}/argo-cd"

argocd_namespace: argocd
argocd_alias: argocd

argocd_helm_ingress: true

# Define the Vault server that will be used by the argo cd vault plugin.
argocd_vault_server: "https://vault{{ environment_name is regex('^dev\\d+$') | ternary('-ota', '') }}.shs.cjib.minjus.nl:8200"

# Define the images that should be used by plugins:
argocd_init_container_images:
  download_tools: "registry.shs.cloud.cjib.nl/cdinnovatie/kubectl:1.24.16-0"
argocd_extra_container_images:
  cjib_helm_avp: "registry.shs.cloud.cjib.nl/cdinnovatie/kubectl:1.24.16-0"
  cjib_kustomize: "registry.shs.cloud.cjib.nl/cdinnovatie/kubectl:1.24.16-0"

argocd_webhook:
  name: "ArgoCD {{ environment_name | upper }} webhook"
  url: "https://argocd.apps.{{ environment_name }}.cloud.cjib.nl/api/webhook"
  event: "repo:refs_changed"
